# Generated by Django 3.2.8 on 2021-10-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
